# Generated by Django 5.0 on 2023-12-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
